### ISSUE TITLE
[needs investigation] Commenter icon links to host journal's icon page in some styles

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dreamwidth#2146] opened 2017-04-27 14:49 UTC
e.g. https://conuly.dreamwidth.org/2508414.html (style Dawn Flush for Compartmentalize).

Spotted by Clifstan in IRC.

**Comment by momijizukamori** [comment] 2022-11-24 02:25
Closing this as a duplicate of https://github.com/dreamwidth/dreamwidth/issues/3001

**Closed** 2022-11-25 01:24 UTC
Labels: severity: (1) minor, effort: (1) lower, is: bug, type: style system
