### ISSUE TITLE
First clause of last sentence of FAQ 216 is misleading verging on incorrect

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dreamwidth#2905] opened 2021-11-10 11:55 UTC
"Syndicated feed accounts are only visible to logged-in users ..." but although actual syndicated content isn't displayed  in https://xkcd-feed.dreamwidth.org/ when not logged in (it is when logged in as me), clicking on the entry title, "Link", or "(mumble) comments" still gets you to the Dreamwidth copy of the contents.

To reproduce: visit https://xkcd-feed.dreamwidth.org/ while not logged in, however you want to (new browser, anonymous window, or just logging out for testing).
Result: enough syndicated content to click to entry content
Expected: a blank page or an error message (ideally with HTTP 1.1 status 403 or maybe 451)
(That's if the solution is to change behavior to fit documentation, as happened before with number of links for premium accounts. But making the FAQ more accurate is another option.)

**Comment by kareila** [comment] 2022-10-20 21:59
dupe of #2822

**Closed by kareila** 2022-10-20 21:59 UTC
Labels: status: untriaged
