### ISSUE TITLE
Markdown editing mode breaks paragraph breaks in <details> tag

### ISSUE THREAD

**Issue by analpi** [dreamwidth/dreamwidth#3272] opened 2023-08-12 19:06 UTC
When writing comments in Markdown mode, any paragraph breaks inside a &lt;details&gt; tag will pre-emptively end that tag.

[Examples are shown in the comments to this entry.](https://anonmemeviewingaccount.dreamwidth.org/651.html)

**Comment by kareila** [comment] 2023-08-12 19:08
duplicate of #3023

**Closed by kareila** 2023-08-12 19:08 UTC
Labels: status: untriaged
