### ISSUE TITLE
report of City Dragon theme not showing entries for screen reader users

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dreamwidth#1887] opened 2016-10-04 16:23 UTC
http://www.dreamwidth.org/support/see_request?id=34499

City Dragon uses the Tectonic layout.  We need to make sure it's fully accessible for screen readers, and that this isn't just a weird caching issue or gremlins in the style system.

**Comment by srukle** [comment] 2016-10-24 18:01
I'm unable to reproduce this error with Safari, Google Chrome, or Firefox on the desktop. On mobile iOS, I do not have any differing results on Safari or Firefox. I'm not using a custom style sheet. Perhaps the user has something in their custom style sheet?

**Comment by rshatch** [comment] 2019-01-02 21:50
@deborahgu or @kaberett would you be able to have a look and confirm this at some point? It's old and we only have the one report, so I'm inclined to say 'gremlins' but with a11y stuff I'd rather be safe.

**Comment by momijizukamori** [comment] 2022-11-25 01:16
At this point, with no other reports or reproductions, I'm going to close this.

**Closed** 2023-06-14 14:37 UTC
Labels: severity: (1) minor, effort: (2) average, from: support, is: bug, type: style system, status: needs-reproducing
